-- create database and schema
CREATE DATABASE IF NOT EXISTS RETAIL_DB;
CREATE SCHEMA IF NOT EXISTS RETAIL_DB.RAW;
CREATE SCHEMA IF NOT EXISTS RETAIL_DB.STG;
CREATE SCHEMA IF NOT EXISTS RETAIL_DB.MART;

-- file formats and stage
CREATE OR REPLACE FILE FORMAT RETAIL_DB.RAW.CSV_FF
  TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1;

CREATE OR REPLACE STAGE RETAIL_DB.RAW.S3_STAGE
  FILE_FORMAT = RETAIL_DB.RAW.CSV_FF;
