CREATE OR REPLACE TABLE RETAIL_DB.MART.DIM_DATE AS
SELECT DISTINCT order_date AS date_key FROM RETAIL_DB.STG.ORDERS_V;

CREATE OR REPLACE TABLE RETAIL_DB.MART.DIM_CUSTOMER AS
SELECT DISTINCT customer_id FROM RETAIL_DB.STG.ORDERS_V;

CREATE OR REPLACE TABLE RETAIL_DB.MART.FCT_SALES AS
SELECT
  o.order_id, o.order_date AS date_key, o.customer_id,
  o.sku, o.qty, o.price, o.amount
FROM RETAIL_DB.STG.ORDERS_V o;

-- QA
SELECT COUNT(*) AS fct_rows FROM RETAIL_DB.MART.FCT_SALES;
SELECT COUNT(*) AS negative_amounts FROM RETAIL_DB.MART.FCT_SALES WHERE amount < 0;
SELECT COUNT(*) AS dup_orders
FROM (
  SELECT order_id, sku, COUNT(*) c FROM RETAIL_DB.MART.FCT_SALES GROUP BY 1,2 HAVING COUNT(*)>1
);
